# mainnet, testnet, shardnet, betanet are acceptable values for network
# other networks can be used, but optional params below are required
network = "testnet"
# ip address to run server on, default to localhost
ip_address = [127, 0, 0, 1]
# port to expose
port = 3030
# replace with the account id of the public key you will use to sign relay transactions - this should match the account_id in your json file
relayer_account_id = "nomnomnom.testnet"
# replace with public key used to sign relay transactions
relayer_public_key = "ed25519:89GtfFzez3opomVpwa7i4m3nptHtc7Ha514XHMWszQtL"
# replace with json file containing 3 entries: account_id (should match relayer_account_id), public_key, private_key
keys_filename = "nomnomnom.testnet.json"

# ------------------------ OPTIONAL ------------------------
# change to true if you're overriding defaults
override_rpc_conf = false
# only uncomment & change if you want to override defaults set in rpc_conf.rs
#rpc_url = "https://archival-rpc.testnet.near.org"
#wallet_url = "https://wallet.testnet.near.org"
#explorer_transaction_url = "https://explorer.testnet.near.org/transactions/"
#rpc_api_key = ""
