# ip address to run server on, default to localhost
ip_address = [0, 0, 0, 0]
# port to expose
port = 3030
# replace with the account id of the public key you will use to sign relay transactions - this should match the account_id in your json file
relayer_account_id = "nomnomnom.testnet"   # "relayer.pagodaplatform.near"
# replace with json files containing 3 entries: account_id (should match relayer_account_id), public_key, private_key
keys_filenames = [
    "./account_keys/nomnomnom.testnet.json",
    "./account_keys/50407f1203d1cc7eeaa3826838cf0aa77f5c5c656ae0d13d8c8ec6527681aee8.json",
    "./account_keys/63554bb688a12342ba3bed2a586582ea41fcf028be0d5e10be0b86c8bcef123f.json",
    "./account_keys/d298bea0d340a103aa9a33920443b6e4ece2788242dfe9425418921a5dba0a9a.json",
    "./account_keys/d90313b513bd5470ca44205e486f38497c358e800a1a48445e4d2cc096ab163e.json",
] # "relayer.pagodaplatform.json"
# replace with the account id of the public key you will use to sign shared_storage transactions - this should match the account_id in your json file
shared_storage_account_id = "relayer-test.testnet"  # "social-storage.pagodaplatform.near"
# replace with json file containing 3 entries: account_id (should match shared_storage_account_id), public_key, private_key
shared_storage_keys_filename = "relayer-test.testnet.json"  # "social-storage.pagodaplatform.json"
# whitelisted contract ids (receiver_id) i.e. ["social.near", "devgovgigs.near"] for mainnet
whitelisted_contracts = ["social-storage.pagodaplatform.near", "relayer.pagodaplatform.near", "social.near", "devgovgigs.near", "near", "account_creator.near", "consensus.neartasks.near", "nearhorizon.near", "relayer_test0.testnet"]
# check if this is a whitelisted sender - to run without this feature, then set use_fastauth_features = false below
whitelisted_delegate_action_receiver_ids = ["account_creator.near", "relayer_test1.testnet", "social.near"]
# if this is set to false, just call /send_meta_tx or /relay endpoints. All other endpoints are coupled with using redis
# this needs to be set to true if use_fastauth_features = true
use_redis = false
# redis url for storing and retrieving allowance for an account_id and seeing if an oauth_token has been used before
redis_url = "redis://127.0.0.1:6379"

# set use_fastauth_features to true if you're integrating with fastauth -
# including check if sender id and receiver id are the same AND (AddKey or DeleteKey action) in process_signed_delegate_action fn
# and you're using shared storage contract
use_fastauth_features = false
# you can still use shared storage without fastauth features if you desire
use_shared_storage = false
social_db_contract_id = "v1.social08.testnet"

# Uncoment the network you want to use or add your own

# mainnet
# rpc_url = "https://rpc.mainnet.near.org"
# wallet_url = "https://wallet.mainnet.near.org"
# explorer_transaction_url = "https://explorer.mainnet.near.org/transactions/"
# rpc_api_key = ""

# testnet
rpc_url = "https://archival-rpc.testnet.near.org"
wallet_url = "https://wallet.testnet.near.org"
explorer_transaction_url = "https://explorer.testnet.near.org/transactions/"
rpc_api_key = ""

# betanet
# rpc_url = "https://rpc.betanet.near.org"
# wallet_url = "https://wallet.betanet.near.org"
# explorer_transaction_url = "https://explorer.betanet.near.org/transactions/"
# rpc_api_key = ""

# shardnet
# rpc_url = "https://rpc.shardnet.near.org"
# wallet_url = "https://wallet.shardnet.near.org"
# explorer_transaction_url = "https://explorer.shardnet.near.org/transactions/"
# rpc_api_key = ""
