# mainnet, testnet, shardnet, betanet are acceptable values for network
network = "testnet"
# replace with the account id of the public key you will use to sign relay transactions
relayer_account_id = "nomnomnom.testnet"
# replace with json file containing 3 entries: account_id (should match relayer_account_id), public_key, private_key
keys_filename = "nomnomnom.testnet.json"
