name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: rust-clippy-check
      # You may pin to the exact commit or the version.
      # uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d
      uses: actions-rs/clippy-check@v1.0.7
      with:
        # GitHub token
        token: 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
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        # toolchain: # optional
        # Arguments for the cargo command
        # args: # optional
        # Use cross instead of cargo
        # use-cross: # optional
        # Display name of the created GitHub check. Must be unique across several actions-rs/clippy-check invocations.
        # name: # optional, default is clippy
